# Generated by Django 5.2.8 on 2025-11-26 10:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attendance_grace_period', models.IntegerField(default=15, help_text='Grace period in minutes')),
                ('passing_marks_percentage', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_lectures_per_day', models.IntegerField(default=8)),
                ('class_duration_minutes', models.IntegerField(default=50)),
                ('break_duration_minutes', models.IntegerField(default=10)),
                ('enable_absence_alerts', models.BooleanField(default=True)),
                ('enable_low_performance_alerts', models.BooleanField(default=True)),
                ('performance_alert_threshold', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_settings', to='core.tenant')),
            ],
            options={
                'db_table': 'department_settings',
            },
        ),
        migrations.CreateModel(
            name='DepartmentAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('meeting', 'Meeting'), ('event', 'Event'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Department Members'), ('faculty', 'Faculty Only'), ('students', 'Students Only')], default='all', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=3, help_text='1=Low, 3=Normal, 5=High', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_announcements_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_announcements', to='core.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_announcements', to='core.tenant')),
            ],
            options={
                'db_table': 'department_announcements',
                'ordering': ['-is_pinned', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['department', 'created_at'], name='department__departm_6e3159_idx'), models.Index(fields=['is_pinned', 'priority'], name='department__is_pinn_db5f2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('syllabus', 'Syllabus'), ('notes', 'Notes'), ('question_paper', 'Question Paper'), ('guideline', 'Guideline'), ('form', 'Form'), ('policy', 'Policy'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='department_resources/%Y/%m/')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all department members')),
                ('download_count', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.department')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='core.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_resources', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'department_resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', 'resource_type'], name='department__departm_1a8229_idx'), models.Index(fields=['subject'], name='department__subject_9f4e50_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacultyMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('agenda', models.TextField()),
                ('minutes', models.TextField(blank=True, help_text='Meeting minutes/notes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('attendees', models.ManyToManyField(blank=True, related_name='faculty_meetings_attended', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_meetings', to='core.department')),
                ('organized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_organized', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_meetings', to='core.tenant')),
            ],
            options={
                'db_table': 'faculty_meetings',
                'ordering': ['-meeting_date', '-start_time'],
                'indexes': [models.Index(fields=['department', 'meeting_date'], name='faculty_mee_departm_ccfe5e_idx'), models.Index(fields=['status'], name='faculty_mee_status_a7da59_idx')],
            },
        ),
    ]
