# Generated by Django 5.2.8 on 2025-11-26 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('inquiry', 'Inquiry'), ('concern', 'Concern'), ('request', 'Request'), ('feedback', 'Feedback'), ('complaint', 'Complaint'), ('appreciation', 'Appreciation')], default='inquiry', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='sent', max_length=20)),
                ('reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role__name': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_communications_sent', to=settings.AUTH_USER_MODEL)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_communication_replies', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_communications_about', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_communications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Communication',
                'verbose_name_plural': 'Parent Communications',
                'db_table': 'parent_communications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', 'status'], name='parent_comm_parent__b79c01_idx'), models.Index(fields=['teacher', 'status'], name='parent_comm_teacher_6c737b_idx'), models.Index(fields=['student', 'created_at'], name='parent_comm_student_c96c80_idx'), models.Index(fields=['priority', 'status'], name='parent_comm_priorit_4f3a38_idx')],
            },
        ),
    ]
