# Generated by Django 5.2.8 on 2025-11-26 09:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year_start_month', models.IntegerField(default=6, help_text='Month when academic year starts (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('semester_system', models.BooleanField(default=True, help_text='True for semester system, False for annual system')),
                ('attendance_grace_minutes', models.IntegerField(default=10, help_text='Grace period for late arrival (in minutes)')),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grading_system', models.CharField(choices=[('percentage', 'Percentage'), ('gpa', 'GPA (4.0 scale)'), ('cgpa', 'CGPA (10.0 scale)'), ('letter', 'Letter Grade')], default='percentage', max_length=20)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('parent_portal_enabled', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/')),
                ('primary_color', models.CharField(default='#667eea', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#764ba2', help_text='Hex color code', max_length=7)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_settings', to='core.tenant')),
            ],
            options={
                'db_table': 'college_settings',
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('mid_term', 'Mid Term'), ('final', 'Final Exam'), ('unit_test', 'Unit Test'), ('practical', 'Practical'), ('viva', 'Viva/Oral')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.academicyear')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.tenant')),
            ],
            options={
                'db_table': 'exam_schedules',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slots', to='college_management.examschedule')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slots', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slots', to='core.subject')),
            ],
            options={
                'db_table': 'exam_slots',
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='For multi-day holidays', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Does this holiday repeat every year?')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.tenant')),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('period_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__name': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedule', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.tenant')),
            ],
            options={
                'db_table': 'timetables',
                'ordering': ['day_of_week', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('event', 'Event'), ('exam', 'Examination'), ('holiday', 'Holiday'), ('urgent', 'Urgent')], max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('teachers', 'Teachers Only'), ('parents', 'Parents Only'), ('department', 'Specific Department'), ('section', 'Specific Section')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.department')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.section')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.tenant')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='announcemen_tenant__79ebe8_idx'), models.Index(fields=['target_audience'], name='announcemen_target__e32955_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['tenant', 'academic_year'], name='exam_schedu_tenant__7ac1de_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['department', 'start_date'], name='exam_schedu_departm_6d17a9_idx'),
        ),
        migrations.AddIndex(
            model_name='examslot',
            index=models.Index(fields=['exam_schedule', 'exam_date'], name='exam_slots_exam_sc_cc7a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='examslot',
            index=models.Index(fields=['section', 'exam_date'], name='exam_slots_section_a5d56d_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['tenant', 'date'], name='holidays_tenant__d92347_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['tenant', 'section', 'day_of_week'], name='timetables_tenant__c35ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher', 'day_of_week'], name='timetables_teacher_bde50f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('section', 'day_of_week', 'period_number', 'academic_year')},
        ),
    ]
