# Generated by Django 5.2.8 on 2025-11-26 10:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('exam', 'Exam Fee'), ('library', 'Library Fee'), ('laboratory', 'Laboratory Fee'), ('sports', 'Sports Fee'), ('transport', 'Transport Fee'), ('hostel', 'Hostel Fee'), ('miscellaneous', 'Miscellaneous')], default='tuition', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online'), ('card', 'Card'), ('upi', 'UPI')], default='online', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='core.section')),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
                'db_table': 'fee_payments',
                'ordering': ['-payment_date', '-due_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='fee_payment_student_26acf6_idx'), models.Index(fields=['fee_type', 'payment_date'], name='fee_payment_fee_typ_e88794_idx'), models.Index(fields=['status', 'due_date'], name='fee_payment_status_7c483c_idx'), models.Index(fields=['receipt_number'], name='fee_payment_receipt_04915a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LibraryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('book_title', models.CharField(max_length=300)),
                ('book_isbn', models.CharField(blank=True, max_length=20)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='issued', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='library_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library Transaction',
                'verbose_name_plural': 'Library Transactions',
                'db_table': 'library_transactions',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='library_tra_student_ac3437_idx'), models.Index(fields=['issue_date', 'due_date'], name='library_tra_issue_d_85e452_idx'), models.Index(fields=['status'], name='library_tra_status_1d15d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('note_date', models.DateField()),
                ('is_important', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes', to='core.subject')),
            ],
            options={
                'verbose_name': 'Student Note',
                'verbose_name_plural': 'Student Notes',
                'db_table': 'student_notes',
                'ordering': ['-note_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'note_date'], name='student_not_student_594eeb_idx'), models.Index(fields=['subject', 'note_date'], name='student_not_subject_97bfdf_idx'), models.Index(fields=['is_important'], name='student_not_is_impo_279acc_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resource_title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('notes', 'Notes'), ('presentation', 'Presentation'), ('video', 'Video'), ('reference', 'Reference Material'), ('worksheet', 'Worksheet'), ('assignment', 'Assignment'), ('other', 'Other')], default='notes', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='student_resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('accessed_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_resources_accessed', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_resources', to='core.subject')),
            ],
            options={
                'verbose_name': 'Student Resource',
                'verbose_name_plural': 'Student Resources',
                'db_table': 'student_resources',
                'ordering': ['-accessed_date'],
                'indexes': [models.Index(fields=['student', 'accessed_date'], name='student_res_student_d8f45a_idx'), models.Index(fields=['resource_type'], name='student_res_resourc_82d6b8_idx'), models.Index(fields=['is_bookmarked'], name='student_res_is_book_0a32e0_idx')],
            },
        ),
    ]
